---
# ============================================================
# Kubernetes Version
# ============================================================

kubernetes_version: "v1.34"

# ============================================================
# Kubernetes Networking
# ============================================================

pod_network_cidr: "10.244.0.0/16"

flannel_interface: eth1  
# ============================================================
# Node IPs
# ============================================================

control_plane_ip: "192.168.56.10"

node_ips:
  controlplane: "192.168.56.10"
  node01: "192.168.56.11"
  node02: "192.168.56.12"

# ============================================================
# Kubernetes Packages
# ============================================================

kubernetes_packages:
  - kubelet
  - kubeadm
  - kubectl

# ============================================================
# Container Runtime
# ============================================================

containerd_package: "containerd"

# ============================================================
# Flannel
# ============================================================

flannel_manifest: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
